### ISSUE TITLE
Server start does not work

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#39]
**Describe the bug**
I did a clean installation on Kali using the default "sudo installer.sh -d" and it went fine, but I could not start the server:
![kép](https://user-images.githubusercontent.com/98665813/163790429-7478d677-23eb-4ef4-800e-6a7be4e88c6a.png)

**To Reproduce**
1. EMBArk installation
$ git clone https://github.com/e-m-b-a/embark.git
$ cd embark
$ sudo ./installer.sh -d
3. Start EMBArk: sudo ./run-server.sh

**Expected behavior**
It used to work the same way a few weeks before. May I install MongoDB manually? I didn't find any error during the installation.

**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.01] & sudo apt full-upgrade -y

**Comment by torabi12** [comment]
I tried again the same installation from the beginning and I got an error and the initialization stopped and prompt got back:
![kép](https://user-images.githubusercontent.com/98665813/163974781-ccb71c2e-6734-4b84-b47d-8580c2b6fe87.png)

I think it used to work before and I don't know what I did wrong because I did not customize anything.

**Comment by BenediktMKuehne** [comment]
apt package for pipenv was removed
-> switching to pip install

**Comment by BenediktMKuehne** [comment]
For a quick fix
`sudo pip3 install pipenv ` 
and then rerun the installer should fix the issue.

-> Fix in  #41

**Comment by torabi12** [comment]
I did it as you suggested,
sudo pip3 install pipenv
sudo ./installer.sh -r

but it is not ok:
![kép](https://user-images.githubusercontent.com/98665813/164200465-b19421ff-ffb7-4d6c-8b8e-788fd6d4ac14.png)


I am going to reinstall the entire VM when the fix will be available.

**Comment by BenediktMKuehne** [comment]
Sorry for closing the issue then.
![](https://user-images.githubusercontent.com/98665813/164200465-b19421ff-ffb7-4d6c-8b8e-788fd6d4ac14.png)
these errors would suggest that the installation didn't succeed.
Is the `pipenv` executable available/installed after using `sudo pip3 install pipenv`?

**Comment by torabi12** [comment]
I think the pipenv install was fine:
![kép](https://user-images.githubusercontent.com/98665813/164227426-a1306703-af4a-4b0d-9eb8-e2d0e0044b61.png)

and I repeated the installation with -r but the line 61 and 82 are still wrong if I start the server.

**Comment by BenediktMKuehne** [comment]
Found the issue, did you specify the `-d` flag when reinstalling?
Without the flag the installer only uninstalls EMBArk.
running `sudo ./installer.sh -rd` would be the correct usage for reinstalling the default-installation.(`sudo ./installer.sh -rF` to change into developer mode etc.)
without that the `-U` option is the same as `-r`

**Comment by BenediktMKuehne** [comment]
Since #41 is now merged you may prefer to update and use that version

**Comment by torabi12** [comment]
I tried with -rd but I got some errors for mysql... component and I couldn't recover the previous Kali, but with a brand new installation it is working fine. Thanks.
